<?php
/**
 *
 *
 * @description:  我起了，一枪秒了，有什么好说的XD
 * @author: shenzheng
 * @time: 2020/1/26 下午5:04
 *
 */


namespace app\origin\controller;

use app\BaseController;

class Auth extends BaseController
{
    public $token = NULL;

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this -> token = $this -> request -> header('access-token');

        if(!$this -> token || !$this -> isLogin()){
            exit("越权操作！");
        }

    }

    public function isLogin(){
        $userInfo = cache(config("redis.token_pre").$this -> token);
        if(!$userInfo){
            return false;
        }
        if(!empty($userInfo['id']) && !empty($userInfo['name'])){
            return true;
        }

        return false;
    }


}